services:
  db:
    image: mongo
    container_name: mongo-test-instance

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-instance
    ports:
        - "8000:8000"
    depends_on:
        - db
    volumes:
        - ./app:/app
