services:
  redis:
    image: redis
    container_name: redis-instance
    command: redis-server
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-instance
    ports:
        - "8000:8000"
    depends_on:
        - redis
    volumes:
        - ./app:/app
