services:
  db:
    image: mongo
    container_name: mongo-instance


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sauce-pipeline-app-instance
    ports:
        - "8501:8501"
    depends_on:
        - db
    volumes:
        - ./app:/app
