APP_NAME = 'Sauce'
DATABASE_NAME = 'sauce'
DATABASE_URL = f'mongodb+srv://username:password@{DATABASE_NAME}.hvhxg.mongodb.net/?retryWrites=true&w=majority&appName={APP_NAME}'
SUBJECTS_COLLECTION_NAME = 'subjects-v4'
MARKETS_COLLECTION_NAME = 'markets-v4'
TEAMS_COLLECTION_NAME = 'teams-v1'
SOURCES_COLLECTION_NAME = 'sources-v1'
